#!/bin/bash

set -eu

# XGD Base Directory Specification
XDG_DATA_HOME="$HOME/.local/share"
XDG_CONFIG_HOME="$HOME/.config/"
XDG_STATE_HOME="$HOME/.local/state"

CURRENTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

$CURRENTDIR/setup_git
$CURRENTDIR/utils
$CURRENTDIR/setup_fish
$CURRENTDIR/setup_fish_plugins

# all installs below assume that fish have been set up
$CURRENTDIR/setup_ruby
$CURRENTDIR/setup_nvm
$CURRENTDIR/setup_rust
$CURRENTDIR/setup_alacritty
$CURRENTDIR/setup_tmux
