#!/bin/bash

set -eu

# XGD Base Directory Specification
XDG_DATA_HOME="$HOME/.local/share"
XDG_CONFIG_HOME="$HOME/.config/"
XDG_STATE_HOME="$HOME/.local/state"

CURRENTDIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# git and standard utils
$CURRENTDIR/setup_git
$CURRENTDIR/utils
$CURRENTDIR/setup_rclone

# tmux
$CURRENTDIR/setup_tmux

# fish and fish plugins
$CURRENTDIR/setup_fish
$CURRENTDIR/setup_fish_plugins

#### all installs below assume that fish has been set up ####
# julia and related
$CURRENTDIR/setup_julia

# ruby and ruby gems
$CURRENTDIR/setup_ruby

# nvm, npm, node
$CURRENTDIR/setup_nvm

# rust and crates
$CURRENTDIR/setup_rust
$CURRENTDIR/setup_alacritty

# nvim and lsp servers
$CURRENTDIR/setup_nvim
$CURRENTDIR/setup_lsp_servers

# pyenv and python stuff
$CURRENTDIR/setup_python
