#!/usr/bin/env fish

if not type -q rustup
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    rustup --version
    fish_add_path $HOME/.cargo/bin/                                                     
    cargo --version
end

# rust crates
cargo install eza 
cargo install --locked navi
cargo install --locked starship
cargo install --git https://github.com/MordechaiHadad/bob.git   # nvim version manager

# add the nvim path
fish_add_path $HOME/.local/share/bob/nvim-bin
