#!/usr/bin/env fish

curl -fsSL https://install.julialang.org | sh
fish_add_path $HOME/.juliaup/bin                                                     
julia --version

# install some basic packages
julia -e 'using Pkg; Pkg.add(["Revise", "Debugger"]);'
