#!/usr/bin/env fish

set NVIM_VERSION "0.9.5"

cd
wget https://github.com/neovim/neovim/releases/download/v$NVIM_VERSION/nvim-linux64.tar.gz
tar -xvf nvim-linux64.tar.gz
fish_add_path $HOME/nvim-linux64/bin/ # add to fish path 

