#!/usr/bin/env fish

# using ruby-install; https://github.com/postmodern/ruby-install#readme
set RUBY_INSTALL_VERSION "0.9.3"
set RUBY_VERSION "3.3.3"
set RUBY_PATH "$HOME/.rubies/ruby-$RUBY_VERSION/bin/"

if not ruby-install --version 
    wget https://github.com/postmodern/ruby-install/releases/download/v$RUBY_INSTALL_VERSION/ruby-install-$RUBY_INSTALL_VERSION.tar.gz
    tar -xzvf ruby-install-$RUBY_INSTALL_VERSION.tar.gz
    rm ruby-install-$RUBY_INSTALL_VERSION.tar.gz
    cd ruby-install-$RUBY_INSTALL_VERSION/
    sudo make install
    cd                                                                      # go back to home
end

# installing latest stable version of ruby
if not test -d $RUBY_PATH
    ruby-install ruby $RUBY_VERSION
    $RUBY_PATH/ruby --version
end
fish_add_path $RUBY_PATH                                                    # add to fish path 

# installing needed ruby gems
gem install colorls
