#!/bin/bash

# followed a tutorial: https://feeblenerd.blogspot.com/2015/11/pretty-i3-with-xfce.html
/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb keyring.deb SHA256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734
sudo apt install ./keyring.deb
echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | sudo tee /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update
sudo apt install i3

# enable touchpad
sudo mkdir -p /etc/X11/xorg.conf.d
sudo echo "
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
EndSection
" > /etc/X11/xorg.conf.d/90-touchpad.conf

# i3-customization: https://itsfoss.com/i3-customization/ 
sudo apt install gnome-themes-standard gtk2-engines-murrine
sudo apt install lxappearance

## tela circle icon theme
cd
git clone https://github.com/vinceliuice/Tela-circle-icon-theme
cd Tela-circle-icon-theme
./install.sh -c black
cd ..
rm -rf Tela-circle-icon-theme

## graphite gtk theme
cd
git clone https://github.com/vinceliuice/Graphite-gtk-theme.git
cd Graphite-gtk-theme
./install.sh --tweaks black
cd ..
rm -rf Graphite-gtk-theme

## from here, use lxappearance to set the theme
