#!/usr/bin/env fish

git clone https://github.com/alacritty/alacritty.git
cd alacritty
cargo build --release

# terminfo file
sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
infocmp alacritty

# desktop entry
sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

# remove the repo
rm -rf alacritty

# Ubuntu Mono Nerd Font; https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/UbuntuMono/Regular
mkdir -p $HOME/.local/share/fonts
wget -O $HOME/.local/share/fonts/font.ttf https://github.com/ryanoasis/nerd-fonts/blob/11ab9428938a6ecbd8d308d6d552d767db6046cc/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFont-Regular.ttf
fc-cache -f -vfc-list | grep "Ubuntu"
