#!/usr/bin/env fish

set PYTHON_VERSION "3.10.12"

if not type -q pyenv
    curl https://pyenv.run | bash

    set -Ux PYENV_ROOT $HOME/.pyenv
    fish_add_path $PYENV_ROOT/bin

    # python build dependencies
    sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
        libbz2-dev libreadline-dev libsqlite3-dev curl git \
        libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

    pyenv install $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
end

# python packages
python3 -m pip install papis tldr jupytext
