#!/bin/bash

# install fish
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install fish
fish --version

# set default shell 
chsh -s $(which fish)                   

# install fisher; https://github.com/jorgebucaran/fisher 
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish > fishfile.fish
source fishfile.fish && fisher install jorgebucaran/fisher
rm fishfile.fish
