#!/bin/bash

# updates
sudo apt update
sudo apt upgrade

sudo apt-get update
sudo apt-get upgrade

# curl
sudo apt install curl
curl --version

# xclip
sudo apt-get install xclip
xclip -version

# fuzzy finder
sudo apt install fzf
fzf --version

# batcat
sudo apt install bat
batcat --version

# ripgrep
sudo apt-get install ripgrep
rg --version

# zathura
sudo apt install zathura
zahura --version

# htop
sudo apt install htop

# glow
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install glow
