import = ["/home/codetalker7/.config/alacritty/themes/dracula.yaml"]

[colors.primary]
background = "#000000"

[font]
size = 11.0

[font.bold]
family = "UbuntuMono Nerd Font"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"
